#include <draw.h>
#include <font_ui16.h>
#include <font_ui20.h>
#include <font_mono16.h>

/*
 * Anti-aliased proportional fonts.  Atlas headers are generated by
 * tools/mkfont.py; each glyph is a (width x line_h) alpha bitmap on a
 * shared baseline, so rendering is a straight alpha blend + advance.
 */

const draw_font_t draw_font_ui = {
    FONT_UI16_LINE_H, font_ui16_widths, font_ui16_offsets, font_ui16_alpha,
};

const draw_font_t draw_font_ui_big = {
    FONT_UI20_LINE_H, font_ui20_widths, font_ui20_offsets, font_ui20_alpha,
};

/* Anti-aliased monospace (Menlo 16px); every glyph advances DRAW_MONO_CW. */
const draw_font_t draw_font_mono = {
    FONT_MONO16_LINE_H, font_mono16_widths, font_mono16_offsets,
    font_mono16_alpha,
};

void draw_rect_alpha(draw_surface_t *s, int x, int y, int w, int h,
                     uint32_t color, unsigned alpha) {
    if (!s || !s->px || alpha == 0) return;
    if (alpha >= 255) { draw_rect(s, x, y, w, h, color); return; }
    int x2 = x + w, y2 = y + h;
    if (x < 0) x = 0;
    if (y < 0) y = 0;
    if (x2 > s->w) x2 = s->w;
    if (y2 > s->h) y2 = s->h;
    for (int yy = y; yy < y2; yy++) {
        uint32_t *row = s->px + yy * s->w;
        for (int xx = x; xx < x2; xx++)
            row[xx] = draw_blend(row[xx], color, alpha);
    }
}

/* Coverage (0..255) of a pixel at corner-distance from the rounded edge.
 * dx,dy are measured from the circle centre; returns how "inside" it is. */
static unsigned corner_cov(int dx, int dy, int r) {
    /* distance^2 vs r^2 with a 1px anti-alias band */
    int d2 = dx * dx + dy * dy;
    int ri = r - 1;
    if (d2 <= ri * ri) return 255;
    if (d2 >= (r + 1) * (r + 1)) return 0;
    /* linear-ish falloff across the 2px band */
    int d = 0;
    while (d * d < d2) d++;            /* ceil(sqrt(d2)) */
    int t = (r + 1 - d) * 127;
    if (t < 0) t = 0;
    if (t > 255) t = 255;
    return (unsigned)t;
}

void draw_round_rect(draw_surface_t *s, int x, int y, int w, int h,
                     int r, uint32_t color) {
    if (!s || !s->px || w <= 0 || h <= 0) return;
    if (r * 2 > w) r = w / 2;
    if (r * 2 > h) r = h / 2;
    if (r < 1) { draw_rect(s, x, y, w, h, color); return; }
    for (int yy = 0; yy < h; yy++) {
        int py = y + yy;
        if (py < 0 || py >= s->h) continue;
        uint32_t *prow = s->px + py * s->w;
        for (int xx = 0; xx < w; xx++) {
            int px = x + xx;
            if (px < 0 || px >= s->w) continue;
            unsigned a = 255;
            int cx = -1, cy = -1;
            if (xx < r && yy < r)            { cx = r - 1 - xx; cy = r - 1 - yy; }
            else if (xx >= w - r && yy < r)  { cx = xx - (w - r); cy = r - 1 - yy; }
            else if (xx < r && yy >= h - r)  { cx = r - 1 - xx; cy = yy - (h - r); }
            else if (xx >= w - r && yy >= h - r) { cx = xx - (w - r); cy = yy - (h - r); }
            if (cx >= 0) {
                a = corner_cov(cx, cy, r);
                if (!a) continue;
            }
            prow[px] = (a >= 255) ? color : draw_blend(prow[px], color, a);
        }
    }
}

void draw_round_frame(draw_surface_t *s, int x, int y, int w, int h,
                      int r, uint32_t color) {
    if (!s || !s->px || w <= 0 || h <= 0) return;
    if (r * 2 > w) r = w / 2;
    if (r * 2 > h) r = h / 2;
    /* straight edges */
    draw_rect(s, x + r, y, w - 2 * r, 1, color);
    draw_rect(s, x + r, y + h - 1, w - 2 * r, 1, color);
    draw_rect(s, x, y + r, 1, h - 2 * r, color);
    draw_rect(s, x + w - 1, y + r, 1, h - 2 * r, color);
    /* corner pixels via the coverage ring (thin band) */
    for (int yy = 0; yy < r; yy++)
        for (int xx = 0; xx < r; xx++) {
            int cx = r - 1 - xx, cy = r - 1 - yy;
            unsigned a = corner_cov(cx, cy, r);
            unsigned inner = corner_cov(cx, cy, r - 1);
            unsigned edge = (a > inner) ? a - inner : 0;
            if (!edge) continue;
            struct { int px, py; } pts[4] = {
                { x + xx, y + yy },
                { x + w - 1 - xx, y + yy },
                { x + xx, y + h - 1 - yy },
                { x + w - 1 - xx, y + h - 1 - yy },
            };
            for (int k = 0; k < 4; k++) {
                if (pts[k].px < 0 || pts[k].px >= s->w ||
                    pts[k].py < 0 || pts[k].py >= s->h) continue;
                uint32_t *p = s->px + pts[k].py * s->w + pts[k].px;
                *p = draw_blend(*p, color, edge);
            }
        }
}

int draw_text_aa(draw_surface_t *s, int x, int y, const char *str,
                 uint32_t color, const draw_font_t *font) {
    int pen = x;

    if (!str || !font) return 0;
    for (; *str; str++) {
        unsigned char ch = (unsigned char)*str;
        if (ch < 32 || ch > 126) ch = '?';
        int gi = ch - 32;
        int gw = font->widths[gi];
        if (s && s->px) {
            const unsigned char *ga = font->alpha + font->offsets[gi];
            for (int gy = 0; gy < font->line_h; gy++) {
                int yy = y + gy;
                if (yy < 0 || yy >= s->h) continue;
                uint32_t *row = s->px + yy * s->w;
                const unsigned char *arow = ga + gy * gw;
                for (int gx = 0; gx < gw; gx++) {
                    unsigned a = arow[gx];
                    if (!a) continue;
                    int xx = pen + gx;
                    if (xx >= 0 && xx < s->w)
                        row[xx] = draw_blend(row[xx], color, a);
                }
            }
        }
        pen += gw;
    }
    return pen - x;
}

int draw_text_width(const char *str, const draw_font_t *font) {
    int w = 0;

    if (!str || !font) return 0;
    for (; *str; str++) {
        unsigned char ch = (unsigned char)*str;
        if (ch < 32 || ch > 126) ch = '?';
        w += font->widths[ch - 32];
    }
    return w;
}
