#!/usr/bin/env python3
"""
mkfont.py — rasterize a host TTF into an anti-aliased glyph atlas C header.

Each glyph (ASCII 32..126) is rendered as an alpha bitmap of size
(advance x line_h) on a shared baseline, so the renderer just blends a
w x line_h block and advances the pen.  Regenerate with:

    python3 tools/mkfont.py

Outputs userspace/include/font_ui16.h and font_ui20.h.
"""
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "userspace", "include")

FONTS = [
    # (header name, symbol prefix, ttf path, px size)
    ("font_ui16.h", "font_ui16", "/System/Library/Fonts/HelveticaNeue.ttc", 15),
    ("font_ui20.h", "font_ui20", "/System/Library/Fonts/HelveticaNeue.ttc", 20),
    # Anti-aliased monospace for the terminal / console / preformatted text.
    ("font_mono16.h", "font_mono16", "/System/Library/Fonts/Menlo.ttc", 16),
]


def build(path, prefix, ttf, px):
    f = ImageFont.truetype(ttf, px)
    ascent, descent = f.getmetrics()
    line_h = ascent + descent

    widths, blobs = [], []
    for code in range(32, 127):
        ch = chr(code)
        adv = max(1, int(round(f.getlength(ch))))
        # Render with 2px slack each side, then crop to the advance box so
        # slight overhangs (e.g. italic-ish curves) are kept where possible.
        img = Image.new("L", (adv + 4, line_h), 0)
        ImageDraw.Draw(img).text((2, 0), ch, font=f, fill=255)
        img = img.crop((2, 0, 2 + adv, line_h))
        widths.append(adv)
        blobs.append(img.tobytes())

    offsets = [0]
    for b in blobs:
        offsets.append(offsets[-1] + len(b))
    alpha = b"".join(blobs)

    with open(path, "w") as out:
        out.write(f"/* Generated by tools/mkfont.py from {os.path.basename(ttf)}"
                  f" @{px}px — do not edit. */\n")
        out.write(f"#define {prefix.upper()}_LINE_H {line_h}\n")
        out.write(f"static const unsigned char {prefix}_widths[95] = {{\n    ")
        out.write(", ".join(str(w) for w in widths))
        out.write("\n};\n")
        out.write(f"static const unsigned int {prefix}_offsets[96] = {{\n    ")
        out.write(", ".join(str(o) for o in offsets))
        out.write("\n};\n")
        out.write(f"static const unsigned char {prefix}_alpha[{len(alpha)}] = {{\n")
        for i in range(0, len(alpha), 20):
            out.write("    " + ",".join(str(b) for b in alpha[i:i + 20]) + ",\n")
        out.write("};\n")
    print(f"{path}: {len(alpha)} alpha bytes, line_h={line_h}")


if __name__ == "__main__":
    for name, prefix, ttf, px in FONTS:
        build(os.path.join(OUT, name), prefix, ttf, px)
