#!/usr/bin/env python3
"""
mkrepo.py — build the MaeroOS package repository.

Reads package recipes from ports/packages/<name>/ (a `pkg.conf` plus the
files to ship), produces repo/ with index.txt + <name>-<ver>.tar (ustar).

pkg.conf format (key=value):
    version=1.0
    caption=One-line description shown in the Store
    exec=/disk/apps/<name>/<binary>     (what the launcher runs)
    fullscreen=1                        (optional: app owns the screen)
    args=-iwad /disk/apps/doom/doom1.wad  (optional launch args)

index.txt format:
    #maeros-index v1 serial=<unix time of the build>
    name|version|size|tarfile|caption|exec|fullscreen|args|rawinput|sha256
    ...
    #sig ed25519 <128 hex: signature over every byte above this line>

sha256 is the hex SHA-256 of the tarball; `pkg install` refuses a download
that does not match it.  Packages are flat: pkg only extracts plain files at
the top level, so a recipe directory must not contain subdirectories.

Signing key: a 32-byte Ed25519 seed, stored as hex in $MAEROS_REPO_KEY or, by
default, ~/.config/maeros/repo-signing.key (mode 0600, never in the tree).
It is created on first use, so a fresh clone needs no setup.  The public half
reaches pkg through userspace/pkg/repo_pubkey.h, which the userspace build
generates with `mkrepo.py --pubkey-header`; pkg rejects an index that this key
did not sign, or whose serial is lower than the cached one.  A repo and a pkg
binary built with different keys do not work together: rebuild both (and the
disk/initrd) after changing the key.
"""
import hashlib
import os
import sys
import tarfile
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ed25519  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKGS = os.path.join(ROOT, "ports", "packages")
REPO = os.path.join(ROOT, "repo")
DEFAULT_KEY = os.path.join(os.path.expanduser("~"), ".config", "maeros",
                           "repo-signing.key")


def key_path():
    return os.environ.get("MAEROS_REPO_KEY") or DEFAULT_KEY


def load_key(path=None):
    """Return the 32-byte signing seed, creating the key file if missing."""
    path = path or key_path()
    if not os.path.exists(path):
        os.makedirs(os.path.dirname(os.path.abspath(path)), mode=0o700,
                    exist_ok=True)
        try:
            fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        except FileExistsError:   # another build created it meanwhile
            pass
        else:
            with os.fdopen(fd, "w") as f:
                f.write(os.urandom(32).hex() + "\n")
            print(f"mkrepo: created repo signing key {path}", file=sys.stderr)
    with open(path) as f:
        seed = bytes.fromhex(f.read().strip())
    if len(seed) != 32:
        sys.exit(f"mkrepo: {path}: expected 64 hex characters")
    return seed


def sign_index(lines, seed, serial):
    """The signed index.txt contents for these package lines."""
    body = f"#maeros-index v1 serial={serial}\n"
    body += "".join(line + "\n" for line in lines)
    sig = ed25519.sign(seed, body.encode())
    return body + f"#sig ed25519 {sig.hex()}\n"


def pubkey_header(out):
    """Write userspace/pkg/repo_pubkey.h, touching it only if it changed."""
    pk = ed25519.public_key(load_key())
    text = ("/* Generated by tools/mkrepo.py --pubkey-header from the repo\n"
            f" * signing key ({key_path()}).  Do not edit. */\n"
            "#pragma once\n#include <stdint.h>\n\n"
            "static const uint8_t repo_pubkey[32] = {\n")
    for i in range(0, 32, 8):
        text += "    " + ", ".join(f"0x{b:02x}" for b in pk[i:i + 8]) + ",\n"
    text += "};\n"
    try:
        with open(out) as f:
            if f.read() == text:
                return
    except FileNotFoundError:
        pass
    with open(out, "w") as f:
        f.write(text)


def read_conf(path):
    conf = {"version": "1.0", "caption": "", "exec": "", "fullscreen": "0",
            "args": "", "rawinput": "0"}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                conf[k.strip()] = v.strip()
    return conf


def main():
    if len(sys.argv) == 3 and sys.argv[1] == "--pubkey-header":
        return pubkey_header(sys.argv[2])
    if len(sys.argv) != 1:
        sys.exit("usage: mkrepo.py [--pubkey-header OUT]")
    seed = load_key()
    os.makedirs(REPO, exist_ok=True)
    index = []
    for name in sorted(os.listdir(PKGS)):
        pdir = os.path.join(PKGS, name)
        confp = os.path.join(pdir, "pkg.conf")
        if not os.path.isdir(pdir) or not os.path.exists(confp):
            continue
        conf = read_conf(confp)
        tar_name = f"{name}-{conf['version']}.tar"
        tar_path = os.path.join(REPO, tar_name)
        with tarfile.open(tar_path, "w", format=tarfile.USTAR_FORMAT) as tf:
            for fn in sorted(os.listdir(pdir)):
                if fn == "pkg.conf":
                    continue
                src = os.path.join(pdir, fn)
                if os.path.islink(src) or not os.path.isfile(src):
                    sys.exit(f"mkrepo: {name}/{fn}: packages may only "
                             "contain regular files at the top level")
                tf.add(src, arcname=fn)
        size = os.path.getsize(tar_path)
        with open(tar_path, "rb") as f:
            digest = hashlib.sha256(f.read()).hexdigest()
        index.append("|".join([
            name, conf["version"], str(size), tar_name, conf["caption"],
            conf["exec"], conf["fullscreen"], conf["args"],
            conf["rawinput"], digest]))
        print(f"  {name} {conf['version']}: {size} bytes")
    with open(os.path.join(REPO, "index.txt"), "w") as f:
        f.write(sign_index(index, seed, int(time.time())))
    print(f"repo: {len(index)} package(s) → {REPO} (signed, key "
          f"{ed25519.public_key(seed).hex()[:16]}…)")


if __name__ == "__main__":
    sys.exit(main())
